=== 2147145-DivyaVPrasad/cat1/NewXMLSchemaCAT1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Company">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Employee" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
						
						
						
							<xs:element name="Emp_name" type="xs:string">
							</xs:element>
						
							<xs:element name="Emp_age" type="xs:integer">
							</xs:element>
							
							<xs:element name="Emp_salary" type="sal">
							</xs:element>
							
							<xs:element name="Emp_emailid" type="xs:string">
							</xs:element>
							
							<xs:element name="Emp_phonenum" type="check">
							</xs:element>
							
							<xs:element name="Emp_designation" type="xs:string">
							</xs:element>
								
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Emp_id" type="xs:integer" use="required" />
			
		</xs:complexType>
	</xs:element>
	
	<xs:simpleType name="sal">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="50000"></xs:minInclusive>
			<xs:maxInclusive value="200000"></xs:maxInclusive>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name = "check">
    <xs:restriction base = "xs:integer">
    <xs:totalDigits value = "10"></xs:totalDigits>
    </xs:restriction>
    </xs:simpleType>
	
	
</xs:schema>

=== 2147145-DivyaVPrasad/cat1/NewFilecatnew.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="NewStylesheetCAT1.xsl" ?>
<Company Emp_id="0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./NewXMLSchemaCAT1.xsd">
  <Employee>
  
    <Emp_name>Divya V Prasad</Emp_name>
    <Emp_age>21</Emp_age>
    <Emp_salary>50000</Emp_salary>
    <Emp_emailid>divyavprasad@gmail.com</Emp_emailid>
    <Emp_phonenum>9667609376</Emp_phonenum>
    <Emp_designation>WebDeveloper</Emp_designation>
  </Employee>
  
  <Employee>
    <Emp_name>Praveen Nair</Emp_name>
    <Emp_age>29</Emp_age>
    <Emp_salary>100000</Emp_salary>
    <Emp_emailid>praveenprasad@gmail.com</Emp_emailid>
    <Emp_phonenum>9667309376</Emp_phonenum>
    <Emp_designation>JavaDeveloper</Emp_designation>
  </Employee>
  
  <Employee>
    <Emp_name>Sukhwinder Singh</Emp_name>
    <Emp_age>31</Emp_age>
    <Emp_salary>50000</Emp_salary>
    <Emp_emailid>sukhvinder@gmail.com</Emp_emailid>
    <Emp_phonenum>9667609376</Emp_phonenum>
    <Emp_designation>TeamLeader</Emp_designation>
  </Employee>
</Company>
